from tg_bot.keyboards.inline.settings_buttons import NEXT, PREV, MAIN_MENU
from tg_bot.keyboards.inline.settings_keyboards import create_settings_keyboard_general, create_settings_keyboard_subgeneral
